# Convolution
import numpy as np
import matplotlib.pyplot as plt
n = np.arange(0, 10)
x = np.heaviside(n, 1)
h = np.heaviside(n - 3, 1)
y = np.convolve(x, h)
plt.figure(figsize=(8, 6))
plt.stem(n, x, use_line_collection=True)
plt.title('x(n) = u(n)')
plt.xlabel('n')
plt.ylabel('Amplitude')
plt.grid(True)
plt.show()
plt.figure(figsize=(8, 6))
plt.stem(n, h, use_line_collection=True)
plt.title('h(n) = u(n-3)')
plt.xlabel('n')
plt.ylabel('Amplitude')
plt.grid(True)
plt.show()
plt.figure(figsize=(8, 6))
plt.stem(np.arange(0, len(y)), y, use_line_collection=True)
plt.title('y(n) = x(n) * h(n)')
plt.xlabel('n')
plt.ylabel('Amplitude')
plt.grid(True)
plt.show()