import numpy as np
import matplotlib.pyplot as plt
t = np.linspace(-2*np.pi, 2*np.pi, 1000)
x = np.cos(t) + 0.5*np.cos(3*t) + 0.2*np.cos(5*t)
plt.plot(t, x)
plt.title('Input signal x(t)')
plt.xlabel('Time (s)')
plt.show()
N = len(x)
n = np.arange(N)
k = n.reshape((N, 1))
exp_term = np.exp(-2j * np.pi * k * n / N)
coeff = np.dot(exp_term, x)
freq = np.fft.fftfreq(N)
idx = np.argsort(freq)
freq = freq[idx]
coeff = coeff[idx]
plt.stem(freq, np.abs(coeff))
plt.title('Frequency spectrum X(f)')
plt.xlabel('Frequency (Hz)')
plt.show()
recon = np.dot(exp_term.T, coeff)
plt.plot(t, recon)
plt.title('Output signal from Fourier series coefficients')
plt.xlabel('Time (s)')
plt.show()
diff = np.abs(x) - np.abs(recon)
plt.plot(t, diff)
plt.title('Difference between the original and reconstructed signals')
plt.xlabel('Time (s)')
plt.show()