import numpy as np
import matplotlib.pyplot as plt
y=np.ones(5)
plt.stem(y)
plt.title('Input signal')
plt.show()
N=len(y)
n=np.arange(N)
k=n.reshape((N,1))
exp_term=np.exp(-2j*np.pi*k*n/N)
coeff=np.dot(exp_term,y)
recon=np.dot(exp_term.T,coeff)
plt.stem(np.real(recon))
plt.title('Output signal from Fourier series coefficients')
plt.show()
diff=np.abs(y)-np.abs(recon)
plt.stem(diff)
plt.title('Difference between the original and reconstucted signals')
plt.show() 