# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/ALL PROGRAMMING LANGUAGES/VERLIOG/2bitadders/2bitadders.cache/wt} [current_project]
set_property parent.project_path {D:/ALL PROGRAMMING LANGUAGES/VERLIOG/2bitadders/2bitadders.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {D:/ALL PROGRAMMING LANGUAGES/VERLIOG/fa2/fa2.srcs/sources_1/new/fulladder.v}
  {D:/ALL PROGRAMMING LANGUAGES/VERLIOG/2bitadders/2bitadders.srcs/sources_1/new/code.v}
  {D:/ALL PROGRAMMING LANGUAGES/VERLIOG/halfadder3/halfadder3.srcs/sources_1/new/halfadder.v}
}
read_xdc D:/Zybo-Master.xdc
set_property used_in_implementation false [get_files D:/Zybo-Master.xdc]

synth_design -top fulladder -part xc7z010clg400-1
write_checkpoint -noxdef fulladder.dcp
catch { report_utilization -file fulladder_utilization_synth.rpt -pb fulladder_utilization_synth.pb }
