clc;
clear all;
close all;
I = imread('fruit_gray.png');
imshow(I);
I_igs = quantize(I,4,'igs');
I_no_igs = quantize(I,4);
figure;
imshow(I_igs);
figure;
imshow(I_no_igs);
imwrite(I_igs,'fruit_gray_igs.png');
imwrite(I_no_igs,'fruit_gray_no_igs.png');
fileinfo = dir('fruit_gray.png');
filesizeOriginal = fileinfo(1).bytes;
fileinfo = dir('fruit_gray_igs.png');
filesizeIGS = fileinfo(1).bytes;
fileinfo = dir('fruit_gray_no_igs.png');
filesizeNoIGS = fileinfo(1).bytes;